import type { Metadata } from "next";
import { Asap, DM_Sans } from "next/font/google";
import Layout from '@/src/components/Layout';
import "../globals.css";

const geistSans = Asap({
  variable: "--font-asap-sans",
  subsets: ["latin"],
});

const geistMono = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vitacore - Desarrollo de software y soluciones digitales",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
